server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://assessment-db:5432/assessmentdb
    username: assessment
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true 