server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://notification-db:5432/notificationdb
    username: notification
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true 