spring:
  application:
    name: attendance-management
  datasource:
    url: jdbc:postgresql://localhost:5432/attendance_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

server:
  port: 8080
  servlet:
    context-path: /api


logging:
  level:
    root: INFO
    com.school.attendance: DEBUG
    org.springframework.cache: TRACE
    org.hibernate.SQL: DEBUG

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8081/auth}
  realm: attendance-realm
  resource: attendance-client
  public-client: true
  ssl-required: external

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  packages-to-scan: com.school.attendance.controller
  paths-to-match: /api/**
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
